// Runs after `astro build`: gives every Markdown twin (/blog/<slug>.md) its own header rule —
// Cloudflare's _headers placeholders can't match "<slug>.md" inside one path segment, and a broad
// /blog/* rule would shadow these, so each file gets an exact rule.
// The Link header tells search engines the HTML article is the canonical version.
import { readdirSync, appendFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';

const dist = resolve(import.meta.dirname, '../dist');
const blog = join(dist, 'blog');
if (!existsSync(blog)) process.exit(0);

const rules = readdirSync(blog)
  .filter(f => f.endsWith('.md'))
  .map(f => {
    const slug = f.slice(0, -3);
    return `/blog/${f}\n  Content-Type: text/markdown; charset=utf-8\n  Access-Control-Allow-Origin: *\n  X-Robots-Tag: noindex\n  Link: <https://geoli.eu/blog/${slug}/>; rel="canonical"\n`;
  });

if (rules.length) {
  appendFileSync(join(dist, '_headers'), `\n# Generated by scripts/postbuild.mjs\n${rules.join('')}`);
  console.log(`postbuild: header rules for ${rules.length} Markdown article(s)`);
}
